From free5gc

COPY free5gc.conf /usr/src/free5gc/install/etc/free5gc/free5gc.conf
COPY smf.conf /usr/src/free5gc/install/etc/free5gc/freeDiameter/smf.conf

CMD /usr/src/free5gcfree5gc-smfd
CMD tail -f /dev/null
