From free5gc

COPY free5gc.conf /free5gc/install/etc/free5gc/free5gc.conf
COPY smf.conf /free5gc/install/etc/free5gc/freeDiameter/smf.conf

COPY free5gc.conf /free5gc/install/etc/free5gc/free5gc-copy.conf
COPY smf.conf /free5gc/install/etc/free5gc/freeDiameter/smf-copy.conf

#CMD ./free5gcfree5gc-smfd
CMD tail -f /dev/null
