From free5gc

COPY free5gc.conf /usr/src/free5gc/install/etc/free5gc/free5gc.conf
COPY amf.conf /usr/src/free5gc/install/etc/free5gc/freeDiameter/amf.conf

EXPOSE 36412

CMD /usr/src/free5gc/free5gc-amfd
CMD tail -f /dev/null

