From free5gc

COPY free5gc.conf /free5gc/install/etc/free5gc/free5gc.conf
COPY pcrf.conf /free5gc/install/etc/free5gc/freeDiameter/pcrf.conf


COPY free5gc.conf /free5gc/install/etc/free5gc/free5gc-copy.conf
COPY pcrf.conf /free5gc/install/etc/free5gc/freeDiameter/pcrf-copy.conf

#CMD ./nextepc-pcrfd
CMD tail -f /dev/null
