From free5gc

COPY free5gc.conf /usr/src/free5gc/install/etc/free5gc/free5gc.conf
COPY pcrf.conf /usr/src/free5gc/install/etc/free5gc/freeDiameter/pcrf.conf

CMD /usr/src/free5gc/nextepc-pcrfd
CMD tail -f /dev/null
