From free5gc

COPY free5gc.conf /free5gc/install/etc/free5gc/free5gc.conf
COPY hss.conf /free5gc/install/etc/free5gc/freeDiameter/hss.conf

#só pra salvar em outro lugar
COPY free5gc.conf /free5gc/install/etc/free5gc/free5gc-copy.conf
COPY hss.conf /free5gc/install/etc/free5gc/freeDiameter/hss-copy.conf

#CMD ./nextepc-hssd
CMD tail -f /dev/null
