From free5gc

COPY free5gc.conf /usr/src/free5gc/install/etc/free5gc/free5gc.conf
COPY hss.conf /usr/src/free5gc/install/etc/free5gc/freeDiameter/hss.conf

CMD /usr/src/free5gc/nextepc-hssd
CMD tail -f /dev/null
